name: CI - Validate macOS

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate macOS
    runs-on: macos-latest
    env:
      branch: ${{ github.ref }}

      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Set up Python 3 libraries
        run: pip3 install --requirement requirements.txt

      - name: Set up PyInstaller
        run: pip3 install pyinstaller

      - name: Build portable executable
        run: pyinstaller couchcrasher.spec

      - name: Validate (List supported persistence methods)
        run: dist/couchcrasher --list-supported-methods

      - name: Validate (Install Payload)
        run: sudo dist/couchcrasher --payload couchcrasher_entry.py

      - name: Upload executable (artifact)
        uses: actions/upload-artifact@v2
        with:
          name: couchcrasher (macOS)
          path: dist/couchcrasher

      - name: Upload executable (release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/couchcrasher
          asset_name: couchcrasher (macOS)
          tag: ${{ github.ref }}
          file_glob: true