name: CI - Validate macOS

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate macOS
    runs-on: macos-latest
    env:
      branch: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Set up Python 3 libraries
        run: pip3 install -r requirements.txt

      - name: Set up PyInstaller
        run: pip3 install pyinstaller

      - name: Build portable executable
        run: pyinstaller couchcrasher.spec

      - name: Validate (List supported persistence methods)
        run: dist/couchcrasher --list-supported-methods

      - name: Validate (Install Payload)
        run: sudo dist/couchcrasher --payload couchcrasher.py