name: CI - Validate Windows (ARM64)

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate Windows (ARM64)
    runs-on: [self-hosted, Windows, ARM64]
    env:
      branch: ${{ github.ref }}

      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3 libraries
        run: pip3 install --requirement requirements.txt

      - name: Set up PyInstaller
        run: pip3 install pyinstaller

      - name: Build portable executable
        run: pyinstaller nekrosis.spec

      - name: Validate (List supported persistence methods)
        run: dist/nekrosis.exe --list-supported-methods

      - name: Validate (Install Payload)
        run: dist/nekrosis.exe --payload nekrosis.py

      - name: Upload executable (artifact)
        uses: actions/upload-artifact@v2
        with:
          name: nekrosis.exe (Windows ARM64)
          path: dist/nekrosis.exe

      - name: Compress executable (release)
        if: github.event_name == 'release'
        run: 7z a -tzip dist/nekrosis-windows-arm64.zip dist/nekrosis.exe

      - name: Upload executable (release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/nekrosis-windows-arm64.zip
          asset_name: nekrosis (Windows ARM64)
          tag: ${{ github.ref }}
          file_glob: true