name: CI - Validate Windows

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate Windows
    runs-on: windows-latest
    env:
      branch: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Set up Python 3 libraries
        run: pip3 install --requirement requirements.txt

      - name: Set up PyInstaller
        run: pip3 install pyinstaller

      - name: Build portable executable
        run: pyinstaller couchcrasher.spec

      - name: Validate (List supported persistence methods)
        run: dist/couchcrasher.exe --list-supported-methods

      - name: Validate (Install Payload)
        run: dist/couchcrasher.exe --payload couchcrasher_entry.py

      - name: Upload executable (artifact)
        uses: actions/upload-artifact@v2
        with:
          name: couchcrasher.exe (Windows)
          path: dist/couchcrasher.exe

      - name: Upload executable (release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/couchcrasher.exe
          asset_name: couchcrasher (Windows)
          tag: ${{ github.ref }}
          file_glob: true