name: CI - Validate Linux (ARM)

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate Linux (ARM)
    runs-on: [self-hosted, Linux, ARM64]
    env:
      branch: ${{ github.ref }}

      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3 libraries
        run: pip3 install --requirement requirements.txt

      - name: Set up PyInstaller
        run: pip3 install pyinstaller

      - name: Build portable executable
        run: pyinstaller nekrosis.spec

      - name: Validate (List supported persistence methods)
        run: dist/nekrosis --list-supported-methods

      - name: Validate (Install Payload)
        run: dist/nekrosis --payload nekrosis_entry.py

      - name: Upload executable (artifact)
        uses: actions/upload-artifact@v2
        with:
          name: nekrosis (Linux ARM64)
          path: dist/nekrosis

      - name: Compress executable (release)
        if: github.event_name == 'release'
        run: tar -czvf dist/nekrosis-linux-arm64.tar.gz dist/nekrosis

      - name: Upload executable (release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/nekrosis-linux-arm64.tar.gz
          asset_name: nekrosis (Linux ARM64)
          tag: ${{ github.ref }}
          file_glob: true