name: CI - Validate macOS (Universal)

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate macOS (Universal)
    runs-on: macos-latest
    env:
      branch: ${{ github.ref }}

      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Force Universal 2 charset-normalizer
        run: |
          pip3 download --platform macosx_10_9_universal2 --only-binary=:all: charset-normalizer
          pip3 install charset_normalizer-*-macosx_10_9_universal2.whl

      - name: Set up Python 3 libraries
        run: pip3 install --requirement requirements.txt

      - name: Set up PyInstaller
        run: pip3 install pyinstaller

      - name: Build portable executable
        run: pyinstaller nekrosis.spec

      - name: Validate (List supported persistence methods)
        run: dist/nekrosis --list-supported-methods

      - name: Validate (Install Payload)
        run: sudo dist/nekrosis --payload nekrosis.py

      - name: Upload executable (artifact)
        uses: actions/upload-artifact@v2
        with:
          name: nekrosis (macOS Universal)
          path: dist/nekrosis

      - name: Compress executable (release)
        if: github.event_name == 'release'
        run: ditto -c -k --sequesterRsrc --keepParent dist/nekrosis dist/nekrosis-macOS-universal.zip

      - name: Upload executable (release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/nekrosis-macOS-universal.zip
          asset_name: nekrosis (macOS Universal)
          tag: ${{ github.ref }}
          file_glob: true